### ISSUE TITLE
재학증명서 인증 오류

### ISSUE THREAD

**Issue by ahapwhs0414** [hackersground-kr/GitHubStudentDeveloperPack#1]
https://github.com/hackersground-kr/GitHubStudentDeveloperPack/assets/81242448/e8799196-521f-4614-9ef1-d9a8d1deb6a6

쿠키 초기화 및 쿠키 허용했는데 아무런 변화가 안생깁니다. 엣지랑 크롬 모두 해봤는데 둘 다 똑같이 반응합니다. 파일이 잘못된건가 생각해서 여러 사진을 찍어서도 pdf 변환해서도 올렸는데 전부다 변화가 없습니다.

**Comment by pmj-chosim** [comment]
1. 파일명 영어로 바꿔보기
2. 파일 사이즈 줄이기(500K 정도)
3. 영문 재학 증명서 원본 다운 후, 해당 파일을 캡처하시거나 사진으로 변환 후(500K 정도의 크기 사진) 재업로드

이렇게 위 3가지 방법대로 진행해보시고, 안 되신다면
GitHub에 문의해보시는 것이 좋을 것 같습니다.

**Comment by ahapwhs0414** [comment]
감사합니다 용량을 줄이니 해결되었습니다
